services:
  capella:
    image: ghcr.io/dsd-dbs/capella-dockerimages/capella/remote:6.0.0-selected-dropins-338-merge
    ports:
      - "8088:10000"
      - "5007:5007"
    environment:
      - CONNECTION_METHOD=xpra
      - XPRA_SUBPATH="/"
      - XPRA_CSP_ORIGIN_HOST=http://localhost:8000
    volumes:
      - ./training:/training
      - ./workspace:/workspace
      - ./dropins:/opt/capella/dropins
  app:
    image: ghcr.io/dsd-dbs/capella-trainer/capella-trainer:main
    volumes:
      - ./training:/app/training
    ports:
      - "8000:8000"
    environment:
      - CAPELLA_ENDPOINT=http://capella:5007/api/v1