/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Training */
        get: operations["get_training_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/training/lesson/{lesson_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training Lesson */
        get: operations["training_lesson_training_lesson__lesson_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/training/lesson/{lesson_path}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Training Lesson Checks */
        post: operations["run_training_lesson_checks_training_lesson__lesson_path__checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Folder */
        Folder: {
            /**
             * Name
             * @description Display name of the element.
             */
            name: string;
            /**
             * Path
             * @description Path to the element.
             */
            path: string[];
            /**
             * Slug
             * @description Filename of the element.
             */
            slug: string;
            /**
             * Type
             * @description Type of the element.
             * @default folder
             */
            type: string;
            /**
             * Children
             * @description List of lessons and folders.
             */
            children: (components["schemas"]["Folder"] | components["schemas"]["Lesson"])[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Lesson */
        Lesson: {
            /**
             * Name
             * @description Display name of the element.
             */
            name: string;
            /**
             * Path
             * @description Path to the element.
             */
            path: string[];
            /**
             * Slug
             * @description Filename of the element.
             */
            slug: string;
            /**
             * Type
             * @description Type of the element.
             * @default lesson
             */
            type: string;
            /**
             * Content
             * @description Markdown content
             */
            content: string;
            /**
             * Has Tasks
             * @description Whether the lesson has tasks.
             * @default false
             */
            has_tasks: boolean;
            /**
             * Has Start Model
             * @description Whether the lesson has a start model.
             * @default false
             */
            has_start_model: boolean;
            /**
             * Has End Model
             * @description Whether the lesson has an end model.
             * @default false
             */
            has_end_model: boolean;
        };
        /** TaskResult */
        TaskResult: {
            /** Description */
            description: string;
            /** Was Executed */
            was_executed: boolean;
            /** Success */
            success: boolean;
            /** Message */
            message: string | null;
        };
        /** Training */
        Training: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Author */
            author: string;
            /** Difficulty */
            difficulty: number;
            /** Duration */
            duration: string;
            /** @description Root folder of the training. */
            root: components["schemas"]["Folder"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_training_training_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Training"];
                };
            };
        };
    };
    training_lesson_training_lesson__lesson_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_training_lesson_checks_training_lesson__lesson_path__checks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
