name: "On-Demand Capella Course: Custom Property Values"
description: This is a very cool tutorial that will teach you how to do some very cool stuff.
author: Julius Berges
difficulty: 3
duration: 2h
